name: Code checks

on:
  - push
  - pull_request

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13", "3.14"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: python -m pip install '.[dev,test]'
      - name: Check code
        run: ./code-check.sh
      - name: Build distributions
        run: python -m build
